-- Persistent Synapse agent runs and event stream.
-- Apply after supabase/migration_synapse_agent.sql.

CREATE TABLE IF NOT EXISTS agent_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  conversation_id UUID REFERENCES agent_conversations(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'running' CHECK (status IN ('queued', 'running', 'completed', 'failed', 'cancelled')),
  input JSONB NOT NULL DEFAULT '{}',
  output JSONB NOT NULL DEFAULT '{}',
  error TEXT NOT NULL DEFAULT '',
  metadata JSONB NOT NULL DEFAULT '{}',
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  finished_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_runs_user_created
  ON agent_runs(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_agent_runs_conversation_created
  ON agent_runs(conversation_id, created_at DESC);

CREATE TABLE IF NOT EXISTS agent_run_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id UUID NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  conversation_id UUID REFERENCES agent_conversations(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL,
  sequence BIGINT GENERATED BY DEFAULT AS IDENTITY,
  payload JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_run_events_run_sequence
  ON agent_run_events(run_id, sequence ASC);

CREATE INDEX IF NOT EXISTS idx_agent_run_events_user_created
  ON agent_run_events(user_id, created_at DESC);

CREATE OR REPLACE FUNCTION set_agent_runs_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_agent_runs_updated_at ON agent_runs;
CREATE TRIGGER trg_agent_runs_updated_at
  BEFORE UPDATE ON agent_runs
  FOR EACH ROW
  EXECUTE FUNCTION set_agent_runs_updated_at();

ALTER TABLE agent_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_run_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read own agent runs" ON agent_runs;
CREATE POLICY "Users can read own agent runs" ON agent_runs
  FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can create own agent runs" ON agent_runs;
CREATE POLICY "Users can create own agent runs" ON agent_runs
  FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update own agent runs" ON agent_runs;
CREATE POLICY "Users can update own agent runs" ON agent_runs
  FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can delete own agent runs" ON agent_runs;
CREATE POLICY "Users can delete own agent runs" ON agent_runs
  FOR DELETE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can read own agent run events" ON agent_run_events;
CREATE POLICY "Users can read own agent run events" ON agent_run_events
  FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can create own agent run events" ON agent_run_events;
CREATE POLICY "Users can create own agent run events" ON agent_run_events
  FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can delete own agent run events" ON agent_run_events;
CREATE POLICY "Users can delete own agent run events" ON agent_run_events
  FOR DELETE USING (auth.uid() = user_id);
